### ISSUE TITLE
Lib cannot work with application.yml!

### ISSUE THREAD

**Issue by thesardorbroo** [Nurislom373/Fluent-Doc#2]
Kutubxona `application.yml` bilan ishlay olmayapti. Lekin `application.properties` bo'lsa yaxshi)

**application.properties:**
![image](https://github.com/Nurislom373/Fluent-Doc/assets/103109063/792ef89e-8ec8-4647-90b5-b8ddb71af6b7)

**application.yml**
![image](https://github.com/Nurislom373/Fluent-Doc/assets/103109063/d4e61810-c9b5-4c54-9782-ea5f8b3d3fd1)

**Comment by Nurislom373** [comment]
xato topdim hudo hohlasa keyin releaseda hammasi ishlidi muammosiz hudo hohlasa ✅

**Comment by Nurislom373** [comment]
this bug fixed in 1.0.1 verions
